### ISSUE TITLE
Cards of the declarer are not made available to the opponents in ouvert games

### ISSUE THREAD

**Issue by saescha** [b0n541/jskat#161]
I am developing an AI just for fun in a fork. Now I wonder, how can the AI react to open cards in a ouvert game? I could not find any method in the knowledge class.

**Comment by b0n541** [comment]
Actually this method is supposed to hand over the ouvert cards of the declarer to the knowledge class:

https://github.com/b0n541/jskat/blob/develop/jskat-base/src/main/java/org/jskat/player/AbstractJSkatPlayer.java#L232-L234

Apparently my IDE is telling me that this method is never called. Can you confirm?

**Comment by b0n541** [comment]
Maybe this needs to be done here

https://github.com/b0n541/jskat/blob/develop/jskat-base/src/main/java/org/jskat/control/SkatGame.java#L983

in case of Ouvert games.

**Comment by saescha** [comment]
Yes https://github.com/b0n541/jskat/blob/develop/jskat-base/src/main/java/org/jskat/player/AbstractJSkatPlayer.java#L232-L234 seems never to be called. also I think this implementation does not work. getSinglePlayerCards() creates a new CardList and adds the cards from member singlePlayerCards to it. So adding cards there will not change the singlePlayerCards list in the knowledge object.

**Comment by b0n541** [comment]
Further refactoring is needed to move out discarded cards of the declarer from the GameAnnouncement which should not be handed over to the other players.

**Comment by b0n541** [comment]
Finally managed to fix the issue. Sorry for the delay.

You might want to have a look at the pull request before I merge this to develop?

**Comment by b0n541** [comment]
The important change is that the AI player needs to separate in the game announcement the game contract (suit/grand/null game plus modifiers like hand, ouvert, ouvert cards, schneider, schwarz) from the discarded cards that go back to the Skat. The game contract information (including ouvert cards in ouvert games) is then further shown to the opponent players. I suggest to have a look at the already available AI players that have been adjusted. The important classes are called GameAnnouncement and GameContract.
