### ISSUE TITLE
ramsch in jskat-0.22.0-linux

### ISSUE THREAD

**Issue by Heiko1234567** [b0n541/jskat#172]
Ist der Fehler bereits bekannt? Jedes Ramsch-Spiel ist in der Version skat-0.22.0-linux nicht möglich.
Fehler: Der Skat kann nicht weiter geschoben werden. Drückt man ein paar mal auf den Button: "schieben", stürzt das Programm ab.
Mein System: Ubuntu 22.04.3 LTS / Intel I7-7700HQ /  Grafik: Intel HD 630 / NVidea RTX 1070 / 32 Gb Ram.

**Comment by b0n541** [comment]
Vielen Dank für das Melden des Fehlers. Ich kann das Problem nachstellen.

**Comment by b0n541** [comment]
Ich habe den Fehler gefunden. Leider wird die Behebung einen etwas größeren Umbau nötig machen. Bitte solange die Version 0.21 verwenden.

**Comment by Heiko1234567** [comment]
Ja, danke für die Info. Die 0.21 ist installiert.

**Comment by b0n541** [comment]
Unter https://github.com/b0n541/jskat/actions/runs/7732354462 ist eine gefixte Version verfügbar:

Artifacts -> ubuntu-latest

**Comment by Heiko1234567** [comment]
Das Problrem besteht nach wie vor. Ich kann den Skat beim Ramsch-Spiel nicht weiter schieben. Die Funktion des Button "Schieben" ist nicht ausführbar. Zumindest stürzt das Programm nicht mehr ab, wenn auf Schieben gedrükt wird. Auch kann man jetzt die Karten im Skat tauschen, wie man will - nur es geht halt mit dem Spiel nicht weiter.

**Comment by b0n541** [comment]
Hmm, dann werde ich noch mal schauen müssen.

**Comment by Heiko1234567** [comment]
Wenn man nur Ramsch als Skatserie spielen möchte, funktioniert alles einwandfrei. Wenn in einer normalen Spielserie eine Ramschrunde anfällt (bspw, weil keiner Allein spielen will), dann stellt sich der Fehler ein.

**Comment by Heiko1234567** [comment]
Oder Aufnehmen/Schieben/Drücken, Knopf. Ja, das klingt nach viel Arbeit.

**Comment by b0n541** [comment]
Ich konnte das Problem zunächst ohne komplette Neuimplementierung lösen. Schieben sollte jetzt wieder sowohl in einer Pflichtramschrunde als auch bei einem Ramsch nach fehlenden Reizgeboten funktionieren. Nach den Fehlermeldungen über ungültige Karten im Skat funktioniert das Schieben auch wieder.

Das Ganze kann mit dem letzten erfolgreichen Build ausprobiert werden:

https://github.com/b0n541/jskat/actions/runs/8030903791

**Comment by Heiko1234567** [comment]
Ich hab's grad mal ausprobiert. Der Skat lässt sich nun aufnehmen, aber kommt als gedrückt vom letzten (der drückt in der Runde) zurück und wird angezeigt. Austauschen kann man nun ein zweites mal und per Button "schieben" l(einzige Option)  lässt sich das Spiel nicht weiter spielen.

**Comment by b0n541** [comment]
Hmm, ich habe die oben verlinkte version ausprobiert und tatsächlich ist die weiterhin kaputt. Die neuesten Builds sollten aber funktionieren. Habe es selbst gerade noch einmal getestet:

https://github.com/b0n541/jskat/actions/runs/8162177055

**Comment by Heiko1234567** [comment]
Jetzt ist es prima. Funktioniert - danke!

**Comment by b0n541** [comment]
Vielen Dank für's Testen und die Geduld bis zur Lösung.

**Comment by b0n541** [comment]
Ich habe gerade eine neue Version 0.23 von JSkat erstellt, welche auch noch weitere Bugfixes für Ramsch enthält:

https://github.com/b0n541/jskat/releases/tag/v0.23.0
